module.exports = function() {
    return {
        products: 
        [
            {id: 1, image: '/assets/images/Marcy_Pro_Smith.jpg', name: 'Marcy Pro Smith Machine Weight Bench Home Gym', category: 'Workout Equipment', description: 'All-in-One Station - You don’t have to switch between various workout stations with this gym system that combines different strength building machines: a Power Tower, Utility Bench, and Squat Rack. It also has a dedicated landmine exercise attachment.', price: 1649},
            {id: 2, image: '/assets/images/Commercial_Home_Gym.jpg', name: 'Commercial Home Gym - Smith Machine, Cables with Built in 160 kg Weights', category: 'Workout Equipment', description: 'Smith Machine with 12 adjustable heights. High tension 2000 lb cross cables with 16 adjustable heights. 1:1 pull ratio.', price: 3599},
            {id: 3, image: '/assets/images/Saucony_Trail_Running_Shoe.jpg', name: 'Saucony Men\'s Mad River TR Trail Running Shoe', category: 'Workout Apparel', description: 'PWRFOAM midsole, EVERUN topsole construction for continuous cushioning throughout the run, PWRTRAC tacky rubber, combined with a dual compound outsole, and rugged directional lugs for confidence on any surface at any speed.', price: 145.99},
            {id: 4, image: '/assets/images/Carhartt_Deluxe_Cooler.jpg', name: 'Carhartt Deluxe Dual Compartment Insulated Lunch Cooler Bag, Black', category: 'Workout Accessories', description: 'Dual compartment insulated lunch bag made of heavy duty fabric with Rain Defender durable water repellent, Insulated main compartment keeps food and drinks cool and is large enough for a 6-pack.',price: 24.99},
            {id: 5, image: '/assets/images/Under_Armour_T-Shirt.jpg', name: 'Under Armour Men\'s Tech 2.0 Short Sleeve T-Shirt', category: 'Workout Apparel', description: 'UA Tech fabric is quick-drying, ultra-soft & has a more natural feel.', price: 18.57},
            {id: 6, image: '/assets/images/Calvin_Klein_Euphoria.jpg', name: 'Calvin Klein Deep Euphoria Eau de Parfum, 3.4 Fl Oz', category: 'Fragrances', description: 'Deep euphoria is a new expression of euphoric fantasy. The scent opens with notes of cascalone and black magic rose enhancing the signature of sensuality and modern femininity. The drydown of musk brings a smooth, sensual texture immersing you deep within the fragrance, evoking warmth and pleasure.', price: 99},
            {id: 7, image: '/assets/images/Calvin_Klein_Eternity.jpg', name: 'Calvin Klein Eternity Eau de Parfum, 3.3 Oz', category: 'Fragrances', description: 'The signature scent of an all out romantic, Eternity Eau de Parfumby Calvin Klein transitions beautifully from day to evening. A hymn to love, Eternity opens with notes of mandarin and freesia then delivers a bouquet of beautiful flowers: lily of the valley, violet and spicy carnation. Gentle sandalwood lingers in the dry down.', price: 92},
            {id: 8, image: '/assets/images/Letscom_Fitness_Tracker.jpg', name: 'LETSCOM Fitness Tracker HR', category: 'Workout Accessories', description: 'Cycling Stationary Bike ,Adjustable Handlebar and Seat, Magnetic Resistance Ultra-Quiet Fitness Equipment for Home Workout, Heavy Duty Flywheel (44 Lbs).', price: 439.99},
            {id: 10, image: '/assets/images/HouseFit_Water_Rower.jpg', name: 'HouseFit Water Rower Rowing Machine', category: 'Stationary Equipment', description: 'HouseFit Water Rower Rowing Machine 330Lbs Weight Capacity for Home use Water Resistance Row Machine Exercise with iPad and Phone Support LCD Digital Monitor.', price: 379.99},
            {id: 11, image: '/assets/images/Kindle_PaperWhite_Sage.jpg', name: 'Kindle Paperwhite – Now Waterproof with more than 2x the Storage', category: 'Tech', description: 'Our thinnest, lightest Kindle Paperwhite yet, with a sleek, modern design so you can read comfortably for hours. Features our signature 300 ppi, glare-free Paperwhite display, laser-quality text, and twice the storage of the previous generation. Plus a single battery charge lasts weeks, not hours.', price: 159.99},
            {id: 11, image: '/assets/images/HMC_Indoor_Exercise_Bike.jpg', name: 'HMC Indoor Exercise Bike', category: 'Stationary Equipment', description: 'Cycling Stationary Bike ,Adjustable Handlebar and Seat, Magnetic Resistance Ultra-Quiet Fitness Equipment for Home Workout, Heavy Duty Flywheel (44 Lbs).', price: 439.99},
        ],
        orders: []
    }
}